
// *************************************************************
//                Generated file: do not edit
// This file was generated by schema-to-types npm library
// More info: https://github.com/OlivierChirouze/schema-to-types
// *************************************************************
export interface MessageBase {
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}

export interface Source {
    domain: string;
    timestamp: number;
    signature: string;
}

export interface Id {
    version: number;
    type: string;
    persisted?: boolean;
    value: string;
    source: Source;
}

export interface Preferences {
    version: number;
    data: { opt_in: boolean };
    source: Source;
}

export interface IdAndPrefs {
    preferences: Preferences;
    identifiers: Id[];
}

export interface IdAndOptionalPrefs {
    preferences?: Preferences;
    identifiers: Id[];
}

export interface GetIdPrefsRequest {
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}

export interface GetIdPrefsResponse {
    body: IdAndOptionalPrefs;
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}

export interface PostIdPrefsRequest {
    body: IdAndPrefs;
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}

export interface PostIdPrefsResponse {
    body: IdAndOptionalPrefs;
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}

export interface GetNewIdRequest {
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}

export interface GetNewIdResponse {
    body: { identifiers: Id[] };
    sender: string;
    receiver: string;
    timestamp: number;
    signature: string;
}
