/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Domain = string;
export type GetIdPrefsRequest = MessageBase;
export type Timestamp = number;
export type Signature = string;
export type GetIdPrefsResponse = MessageBase & {
  body: IdAndOptionalPreferences;
};
export type Version = 0;
export type GetNewIdRequest = MessageBase;
export type GetNewIdResponse = MessageBase & {
  body: {
    identifiers: Id[];
  };
};
export type PostIdPrefsRequest = MessageBase & {
  body: IdAndPreferences;
};
export type PostIdPrefsResponse = MessageBase & {
  body: IdAndPreferences;
};

export interface Root {
  domain?: Domain;
  "get-id-prefs-request"?: GetIdPrefsRequest;
  "get-id-prefs-response"?: GetIdPrefsResponse;
  "get-new-id-request"?: GetNewIdRequest;
  "get-new-id-response"?: GetNewIdResponse;
  "id-and-optional-preferences"?: IdAndOptionalPreferences;
  "id-and-preferences"?: IdAndPreferences;
  id?: Id;
  "message-base"?: MessageBase;
  "post-id-prefs-request"?: PostIdPrefsRequest;
  "post-id-prefs-response"?: PostIdPrefsResponse;
  preferences?: Preferences;
  signature?: Signature;
  source?: Source;
  timestamp?: Timestamp;
  version?: Version;
}
export interface MessageBase {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
}
export interface IdAndOptionalPreferences {
  preferences?: Preferences;
  identifiers: Id[];
}
export interface Preferences {
  version: Version;
  data: {
    opt_in?: boolean;
  };
  source: Source;
}
export interface Source {
  timestamp: Timestamp;
  domain: Domain;
  signature: Signature;
}
export interface Id {
  version: Version;
  type: string;
  persisted?: boolean;
  value: string;
  source: Source;
}
export interface IdAndPreferences {
  preferences: Preferences;
  identifiers: Id[];
}
